### ISSUE TITLE
Inconsistent command format

### ISSUE THREAD

**Issue by blaqkrow** [CS2103AUG2017-T17-B2/main#168]
<img width="1093" alt="screen shot 2017-11-03 at 2 56 29 pm" src="https://user-images.githubusercontent.com/28503035/32362855-3f3b65d8-c0a7-11e7-950c-613aa743cfce.png">

Inconsistent command format
Tried to add an appointment to a contact using this format

a n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 b/O r/Broke his foot during soccer practice t/friends t/owesMoney d/5pm to 9pm tomorrow 

confusing as the way to add appointment when adding a contact is: appt 1 d/5pm to 7pm tomorrow

Should try to include the above formate when adding a person first, else adding an appointment becomes a 2 step process.

**Comment by blaqkrow** [comment]
<img width="1089" alt="screen shot 2017-11-03 at 3 07 30 pm" src="https://user-images.githubusercontent.com/28503035/32363153-cae9e108-c0a8-11e7-9dbd-1b410b1032d0.png">

When deleting a person, appointment does not get deleted

To delete an appointment, i have to use this command: appt INDEX d/off

However, as shown in the image above, I have deleted both Alex Yeoh and Roy Balakrish,  and other contacts, how would I know which index they correspond now since I deleted their contacts?

Should call the delete appointment command together with the delete command to avoid confusion.

**Comment by EricLoh** [comment]
Thanks for the feedback! Fixed!
