### ISSUE TITLE
Could not save data

### ISSUE THREAD

**Issue by lawwman** [CS2103AUG2017-T17-B2/main#169]
![image](https://user-images.githubusercontent.com/28558231/32363073-66fb3aa2-c0a8-11e7-8cd1-3d415b9e63cf.png)

Might be because the jar file is saved in downloads. You might want to update this in your user guide.  I think a solution would be to save the jar file in a folder without another jar file.

**Comment by Jeremylsw** [comment]
@ErnestOYH Update UG accordingly

**Comment by Jeremylsw** [comment]
Updated in UG
