### ISSUE TITLE
Shorthand command

### ISSUE THREAD

**Issue by FrozVentus** [CS2103AUG2017-T17-B2/main#170]
![image](https://user-images.githubusercontent.com/14850414/32363204-0ed69852-c0a9-11e7-8472-0ae2d678b538.png)

The shorthand command "c" correspond to both "clear" and "copy", entering "c" intending for "clear" results in "invalid command format".

**Comment by ErnestOYH** [comment]
This is actually a misinformation on our part. Our clear command now have a different shorthand of "cl". Only copy have the shorthand of "c". We will update the user guide accordingly.
