### ISSUE TITLE
Undo and delete does not delete/undo appointment, leading to confusion

### ISSUE THREAD

**Issue by blaqkrow** [CS2103AUG2017-T17-B2/main#173]
<img width="1089" alt="screen shot 2017-11-03 at 3 07 30 pm" src="https://user-images.githubusercontent.com/28503035/32363547-dda221d2-c0aa-11e7-8496-81758cc3dfc2.png">

When deleting a person, appointment does not get deleted

To delete an appointment, i have to use this command: appt INDEX d/off

However, as shown in the image above, I have deleted both Alex Yeoh and Roy Balakrish, and other contacts, how would I know which index they correspond now since I deleted their contacts?

Should call the delete appointment command together with the delete command to avoid confusion.

**Comment by EricLoh** [comment]
Thanks. Fixed this issue.
