### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by joanneong** [CS2103AUG2017-T17-B2/main#174]
Based on our review of your application, we have a few suggestions to make regarding the current User Interface:

1. The top bar looks more like the bar for command input
I am not sure if this is because I am used to testing my own team application, but the command bar is not as obvious as the result display bar. Furthermore, it might be useful to label the result display bar with some sort of placeholder so that users will not attempt to input commands into the result display.

2. Colour scheme for person card display can be such that the alternate colours are more distinct (i.e. choose pink and red)

3. When commands are invalid/wrong the color becomes green for the commands, which is very difficult to see...

**Comment by FrozVentus** [comment]
![image](https://user-images.githubusercontent.com/14850414/32363770-e7d936da-c0ab-11e7-9e7a-86dd63cf5b25.png)

The "today" icon at the top of the application is difficult to see because it is same colour as the background.

**Comment by Jeremylsw** [comment]
Thanks for the comments.

Joanne-1. Command Input Box - Enter Command here text already implemented to eliminate confusion as to which box is the command box
Joanne-2. Any lighter will result in words not being able to be seen. Changing of word text color to suit the lighter pane color will destroy the theme.
Joanne-3. Resolved
Froz-1. Resolved.

Issue Closed.
