### ISSUE TITLE
General questions to consider regarding the application

### ISSUE THREAD

**Issue by joanneong** [CS2103AUG2017-T17-B2/main#175]
Here are some questions for you guys to think about:

1. Why is it necessary to have tags for the users if this application is for medical professionals?

2. When you add a new person without an appointment, you should display something like "Appointment: None" and for remarks and tags, "Remarks: None" and "Tags: None" respectively

3. What is the point of doing `list reverse`

4. Why not support lower-cases as well for duplicate commands?

**Comment by ErnestOYH** [comment]
For question 1:
The idea of keeping the tags is that they are "flexible" in the way they can be used.
For the case of our application, our users (doctors) can use tags labelled with patient conditions as a clear indicator of what a patient is diagnosed with. 
For example, I can tag "John Doe" with "Cold" and "Anemia" and I would know John have this conditions associated with him.
Perhaps we can update our user guide to inform our users that this can be one of the ways to use the tags.

**Comment by ErnestOYH** [comment]
For question 3:
The functionality of list reverse is to reverse the order of the list.
What MedNus aims to do is to keep the usage of mouse to a minimum, and instead opting for a more keyboard approach.
In situations where a user's contact list is full of contacts, instead of scrolling down to see/check a new contact added, he/she can use "list reverse" to bring the newly added contact to the top.

**Comment by ErnestOYH** [comment]
For question 4:
Can I ask you to clarify more on your point?
Right now our command words are "case insensitive".
Inputs for Name, Address, Email and Bloodtype have specific case checks/changes associated with them.
Are you asking why do inputs such as Remark and Tags have no case checks/changes applied for them?

**Comment by Jeremylsw** [comment]
@EricLoh 
#2 left. Close once resolved and merged

**Comment by Jeremylsw** [comment]
#2 - Created a new issue for this week's enhancement. Closed.
