### ISSUE TITLE
Appointment

### ISSUE THREAD

**Issue by lawwman** [CS2103AUG2017-T17-B2/main#176]
I think it will be better to update your user guide on how to set appointment for dates that are far into the future.

Your current examples are of the format: "appt 1 d/tonight 8pm to 10pm". But if I want to set an appointment for next month, it is confusing.

Perhaps you could add an example like "appt 1 d/2017/12/05" so that new users would not be confused.

**Comment by Jeremylsw** [comment]
@ErnestOYH 
http://natty.joestelmach.com/doc.jsp
Take a look at the documented example and update UG accordingly

**Comment by Jeremylsw** [comment]
Updated UG. Closed.
