### ISSUE TITLE
Apply add command keyboard shortcut (Right key) to edit as well

### ISSUE THREAD

**Issue by Jeremylsw** [CS2103AUG2017-T17-B2/main#96]

**Comment by EricLoh** [comment]
I have updated add command to include apt as well, perhaps you might want to add the keyboard short cut to include that. 
Take note that I might want to change the format of date to natural language, so the end product maybe something like "add n/John Doe d/Meet him next week monday". Therefore only the prefix d/ is needed for now. Thanks!
